steal(
    "funcunit/qunit",
    "vendor/sinon-1.7.3.js"
).then(
    "vendor/sinon-qunit-1.0.0.js"
).then(
    "../../coolcoin.js"
).then(
    "./controllers/core_test.js"
).then(
	"./models/transaction_test.js"
);